### ISSUE TITLE
Error presenting challenge

### ISSUE THREAD

**Issue by jerrita** [imroc/cert-manager-webhook-dnspod#1]
I specified my clusterIssuer in `values.yaml` and deployed it by 
```bash
$ helm install dnspod-hooker roc/cert-manager-webhook-dnspod --namespace cert-manager -f values.yaml
$ cat values.yaml
....
clusterIssuer:
  enabled: true
  name: dnspod
  ttl: 600
  staging: false
  secretId: <A Number>
  secretKey: <My Secret Key>
  email: <My Email>
....
```
But when I try to issue a certificate by following, I failed.
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: prod
spec:
  secretName: wildcard-cert
  issuerRef:
    name: dnspod
    kind: ClusterIssuer
  dnsNames:
  - "*.jerrita.cn"
```

Here's detail for this challenge.
```bash
Spec:
  Authorization URL:  https://acme-v02.api.letsencrypt.org/acme/authz-v3/53147134200
  Dns Name:           jerrita.cn
  Issuer Ref:
    Kind:  ClusterIssuer
    Name:  dnspod
  Key:     C70GxiBffL7og1f9NkP0SpcMRW4UJHoxxRvPXXHOoPA
  Solver:
    dns01:
      Webhook:
        Config:
          Secret Id:  257754
          Secret Key Ref:
            Key:      secret-key
            Name:     dnspod-hooker-cert-manager-webhook-dnspod-secret
          Ttl:        600
        Group Name:   acme.jerrita.cn
        Solver Name:  dnspod
  Token:              ITuoHBla960WGR6lWMSONGEJpZtZhWRQhPr1a7auEb0
  Type:               DNS-01
  URL:                https://acme-v02.api.letsencrypt.org/acme/chall-v3/53147134200/m88caQ
  Wildcard:           true
Status:
  Presented:   false
  Processing:  true
  Reason:      error decoding solver config: json: cannot unmarshal number into Go struct field customDNSProviderConfig.secretId of type string
  State:       pending
Events:
  Type     Reason        Age                    From          Message
  ----     ------        ----                   ----          -------
  Normal   Started       7m54s                  cert-manager  Challenge scheduled for processing
  Warning  PresentError  2m45s (x7 over 7m53s)  cert-manager  Error presenting challenge: error decoding solver config: json: cannot unmarshal number into Go struct field customDNSProviderConfig.secretId of type string
```

How to solve it?
