### ISSUE TITLE
renew 报错

### ISSUE THREAD

**Issue by east4ming** [imroc/cert-manager-webhook-dnspod#5]
你好, 今天 renew 证书, 报以下错误, 请帮忙看一下如何解决, 谢谢!
cert-manager报错:

```
"reason": "PresentError",
 "message": "Error presenting challenge: the server is currently unable to handle the request (post dnspod.acme.imroc.cc)",
```

cert-manager-webhook-dnspod报错:

```
I0430 12:46:46.670500       1 main.go:123] create dnspod client successfully
E0430 12:46:47.333874       1 main.go:204] Failed to get domain id cn.: no domain found in zone cn.
```

版本如下:

![image](https://user-images.githubusercontent.com/13358726/166129665-b0b476a0-453e-4597-bd4f-e94dd0e54e3f.png)

**Comment by imroc** [comment]
证书是之前自动生成了，然后没有改动任何配置，自动renew的时候报错了？

**Comment by imroc** [comment]
多给一些信息，比如certificate, clusterissuer 具体内容

**Comment by east4ming** [comment]
> 证书是之前自动生成了，然后没有改动任何配置，自动renew的时候报错了？

是的, 60天前用您的dnspod 生成的.

**Comment by east4ming** [comment]
> 多给一些信息，比如certificate, clusterissuer 具体内容

certificate 如下:
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager-webhook-dnspod
    meta.helm.sh/release-namespace: cert-manager
  labels:
    app: cert-manager-webhook-dnspod
    app.kubernetes.io/managed-by: Helm
    chart: cert-manager-webhook-dnspod-1.2.0
    heritage: Helm
    release: cert-manager-webhook-dnspod
  name: cert-manager-webhook-dnspod-ca
  namespace: cert-manager
spec:
  commonName: ca.dnspod-webhook.cert-manager
  duration: 43800h0m0s
  isCA: true
  issuerRef:
    name: cert-manager-webhook-dnspod-selfsign
  secretName: cert-manager-webhook-dnspod-ca
```

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager-webhook-dnspod
    meta.helm.sh/release-namespace: cert-manager
  labels:
    app: cert-manager-webhook-dnspod
    app.kubernetes.io/managed-by: Helm
    chart: cert-manager-webhook-dnspod-1.2.0
    heritage: Helm
    release: cert-manager-webhook-dnspod
  name: cert-manager-webhook-dnspod-webhook-tls
  namespace: cert-manager
spec:
  dnsNames:
  - cert-manager-webhook-dnspod
  - cert-manager-webhook-dnspod.cert-manager
  - cert-manager-webhook-dnspod.cert-manager.svc
  duration: 8760h0m0s
  issuerRef:
    name: cert-manager-webhook-dnspod-ca
  secretName: cert-manager-webhook-dnspod-webhook-tls
```

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ewhisper-crt
  namespace: cert-manager
spec:
  dnsNames:
  - ewhisper.cn
  - '*.ewhisper.cn'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: dnspod
  secretName: ewhisper-crt-secret
```

clusterissuer如下:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    meta.helm.sh/release-name: cert-manager-webhook-dnspod
    meta.helm.sh/release-namespace: cert-manager
  labels:
    app: cert-manager-webhook-dnspod
    app.kubernetes.io/managed-by: Helm
    chart: cert-manager-webhook-dnspod-1.2.0
    heritage: Helm
    release: cert-manager-webhook-dnspod
  name: dnspod
spec:
  acme:
    email: cuikaidong@foxmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: cert-manager-webhook-dnspod-letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            secretId: AKIDRhiTyC9qGRKyLSIr89tTr78tPgiU1JL8
            secretKeyRef:
              key: secret-key
              name: cert-manager-webhook-dnspod-secret
            ttl: 600
          groupName: acme.imroc.cc
          solverName: dnspod
```

谢谢!

**Comment by imroc** [comment]
我这边暂时没复现出来，正常情况下应该没问题

**Comment by east4ming** [comment]
> 我这边暂时没复现出来，正常情况下应该没问题

能提供一些排查思路吗? 我这边本地排查一下. 谢谢!
证书要过期了, 比较焦虑.....

**Comment by east4ming** [comment]
> 我这边暂时没复现出来，正常情况下应该没问题

我看了一圈, 之前正常签发证书的 challenge 是这样的:
```yaml
apiVersion: acme.cert-manager.io/v1
kind: Challenge
  name: ewhisper-crt-d7fdc-2449993249-791972292
  namespace: cert-manager
spec:
  authorizationURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/103659441977
  dnsName: ewhisper.cn
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: dnspod
  key: odxVt0Bmbt2voIpZc0XGxH6fMKUguHwatuL15FnThdk
  solver:
    dns01:
      webhook:
        config:
          secretId: AKIDRhiTyC9qGRKyLSIr89tTr78tPgiU1JL8
          secretKeyRef:
            key: secret-key
            name: cert-manager-webhook-dnspod-secret
          ttl: 600
        groupName: acme.imroc.cc
        solverName: dnspod
  token: oFhKSwKKL8tB3A5LiumQn3N2x-4Z90-h8F0RaJWTe1s
  type: DNS-01
  url: https://acme-v02.api.letsencrypt.org/acme/chall-v3/103659441977/HbQSrQ
  wildcard: false
```

🐾 `wildcard: false`

这次 异常的, 是这样的:

```yaml
apiVersion: acme.cert-manager.io/v1
kind: Challenge
metadata:
  creationTimestamp: '2022-04-30T12:45:44Z'
  name: ewhisper-crt-d7fdc-2449993249-3532820168
  namespace: cert-manager
status:
  presented: false
  processing: true
  reason: no domain found in zone cn.
  state: pending
spec:
  authorizationURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/103659441967
  dnsName: ewhisper.cn
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: dnspod
  key: QYLKuSmlK6aWmD64hhExOVWaerv0MZgBqEk5bfRCLAI
  solver:
    dns01:
      webhook:
        config:
          secretId: AKIDRhiTyC9qGRKyLSIr89tTr78tPgiU1JL8
          secretKeyRef:
            key: secret-key
            name: cert-manager-webhook-dnspod-secret
          ttl: 600
        groupName: acme.imroc.cc
        solverName: dnspod
  token: SW6uRUVF-KnVkn0yaiZbA8Y7d0faLqUfS3SzImf1iRY
  type: DNS-01
  url: https://acme-v02.api.letsencrypt.org/acme/chall-v3/103659441967/gilp0A
  wildcard: true
```

`wildcard:` 变为`true` 了, 跟这个有关系吗?
